import { z } from "zod";

/**
 * Client for the VLM report path. Sends only structured facts (measurements +
 * AI-generated segment labels) and receives drafted language. It never sends or
 * receives clinical masks/measurements generated by the model (SaMD §I.2).
 */

export interface ReportMeasurement {
  readonly label: string;
  readonly value: string;
}

export interface ReportSegment {
  readonly index: number;
  readonly label: string;
}

export interface ReportContext {
  readonly studyInstanceUid?: string | undefined;
  readonly seriesInstanceUid?: string | undefined;
  readonly modality?: string | undefined;
  readonly measurements: readonly ReportMeasurement[];
  readonly segments: readonly ReportSegment[];
}

export interface ReportAvailability {
  readonly available: boolean;
  readonly message: string;
}

const AvailabilitySchema = z.object({
  available: z.boolean(),
  message: z.string()
});

const ReportResponseSchema = z.union([
  z.object({ status: z.literal("ok"), text: z.string() }),
  z.object({ status: z.literal("error"), message: z.string() })
]);

export type GenerateReportResult =
  | { readonly ok: true; readonly text: string }
  | { readonly ok: false; readonly message: string };

export async function fetchReportAvailability(
  signal: AbortSignal
): Promise<ReportAvailability> {
  try {
    const response = await fetch("/api/report", { cache: "no-store", signal });
    const payload: unknown = await response.json();
    const parsed = AvailabilitySchema.safeParse(payload);
    if (!parsed.success) {
      return { available: false, message: "Report service status was invalid." };
    }
    return parsed.data;
  } catch (error) {
    if (error instanceof DOMException && error.name === "AbortError") {
      return { available: false, message: "Report status check was cancelled." };
    }
    return { available: false, message: getErrorMessage(error) };
  }
}

export async function generateReport(
  context: ReportContext
): Promise<GenerateReportResult> {
  let response: Response;

  try {
    response = await fetch("/api/report", {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ context }),
      cache: "no-store"
    });
  } catch (error) {
    return { ok: false, message: getErrorMessage(error) };
  }

  let payload: unknown;
  try {
    payload = await response.json();
  } catch (error) {
    return { ok: false, message: `Invalid report response: ${getErrorMessage(error)}` };
  }

  const parsed = ReportResponseSchema.safeParse(payload);
  if (!parsed.success) {
    return { ok: false, message: "Report response did not match the schema." };
  }

  if (parsed.data.status === "error") {
    return { ok: false, message: parsed.data.message };
  }

  return { ok: true, text: parsed.data.text };
}

function getErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message : "Unknown error";
}
